name: Playwright Tests

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Install Playwright Browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Step 5: Run Playwright tests with secrets
      - name: Run Playwright tests
        env:
          UAT_BASE_URL: ${{ secrets.UAT_BASE_URL }}
          UAT_USERNAME: ${{ secrets.UAT_USERNAME }}
          UAT_PASSWORD: ${{ secrets.UAT_PASSWORD }}
        run: npx playwright test --reporter=html

      # Step 6: Upload HTML report
      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
