name: Playwright Tests

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        
      -- name: Run Playwright tests
    env:
    UAT_BASE_URL: ${{ secrets.UAT_BASE_URL }}
    UAT_USERNAME: ${{ secrets.UAT_USERNAME }}
    UAT_PASSWORD: ${{ secrets.UAT_PASSWORD }}
  run: npx playwright test --reporter=html

