name: Playwright Tests

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test --reporter=html

    # ✅ Debug: list files to confirm report exists
    - name: Check if report folder exists
      run: |
        echo "Listing contents of repo root:"
        ls -lah
        echo "Listing contents of playwright-report:"
        ls -lah playwright-report || echo "❌ playwright-report folder missing!"

    # ✅ Upload Pages artifact
    - name: Upload Playwright report
      uses: actions/upload-pages-artifact@v3
      with:
        path: playwright-report/

  deploy:
    needs: test
    runs-on: windows-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # ✅ Debug: confirm artifact download
      - name: List downloaded artifact contents
        run: |
          echo "Listing contents of artifact:"
          ls -lah

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
